class AngestellteFields {
  static const Map<String, Map<String, dynamic>> definitions = {
    'addressCity': {'label': 'Ort', 'type': 'Text'},
    'addressCountry': {'label': 'Land', 'type': 'Text'},
    'addressPostalCode': {'label': 'PLZ', 'type': 'Text'},
    'addressState': {'label': 'Bundesland', 'type': 'Text'},
    'addressStreet': {'label': 'Straße', 'type': 'Text'},
    'assignedUserName': {'label': 'Zugewiesener Benutzer', 'type': 'Text (Readonly)'},
    'auertariflicheZulageBrutto': {'label': 'Außertarifliche Zulage (brutto)', 'type': 'Text (Readonly)'},
    'ausbildungsvergtungBrutto': {'label': 'Ausbildungsvergütung(Brutto):', 'type': 'Text (Readonly)'},
    'austrittsdatum': {'label': 'Austrittsdatum', 'type': 'Datum (Readonly)'},
    'bankkontoInhaber': {'label': 'Bankkonto Inhaber', 'type': 'Text'},
    'benutzername': {'label': 'Benutzername', 'type': 'Text (Readonly)'},
    'bewachungsregisterNummer': {'label': 'Bewachungsregister Nummer', 'type': 'Text (Readonly)'},
    'bic': {'label': 'Bic', 'type': 'Text'},
    'bundesland': {'label': 'Bundesland', 'type': 'Text'},
    'createdAt': {'label': 'Erstellt am', 'type': 'Datum-Uhrzeit (Readonly)'},
    'createdByName': {'label': 'Erstellt von', 'type': 'Text (Readonly)'},
    'description': {'label': 'Beschreibung', 'type': 'Textbox'},
    'ePin': {'label': 'EPin', 'type': 'Text (Readonly)'},
    'einstellungsdatum': {'label': 'Einstellungsdatum', 'type': 'Datum (Readonly)'},
    'emailAddress': {'label': 'E-Mail', 'type': 'Text'},
    'emailAddressIsInvalid': {'label': 'E-Mail ist ungültig', 'type': 'Bool (Readonly)'},
    'emailAddressIsOptedOut': {'label': 'E-Mail ist Opt-Out', 'type': 'Bool (Readonly)'},
    'firstName': {'label': 'Vorname', 'type': 'Text (Readonly)'},
    'geburtsdatum': {'label': 'Geburtsdatum', 'type': 'Datum (Readonly)'},
    'geburtsland': {'label': 'Geburtsland', 'type': 'Text (Readonly)'},
    'geburtsname': {'label': 'Geburtsname', 'type': 'Text (Readonly)'},
    'geburtsort': {'label': 'Geburtsort', 'type': 'Text (Readonly)'},
    'gehalt': {'label': 'Gehalt', 'type': 'Text (Readonly)'},
    'gesamtKrankentage': {'label': 'Gesamt Krankentage:', 'type': 'Text (Readonly)'},
    'gesamtUrlaub': {'label': 'Urlaubs Tage über:', 'type': 'Text (Readonly)'},
    'gesamtVergtungBrutto': {'label': 'GesamtVergütung(Brutto):', 'type': 'Text (Readonly)'},
    'gesamtstundenlohnBrutto': {'label': 'Gesamtstundenlohn (brutto)', 'type': 'Text (Readonly)'},
    'iBAN': {'label': 'IBAN', 'type': 'Text'},
    'internermitarbeiter': {'label': 'Interner Mitarbeiter', 'type': 'Bool (Readonly)'},
    'jackenGre': {'label': 'JackenGröße:', 'type': 'Text'},
    'kinder': {'label': 'Kinder', 'type': 'Ganzzahl (Readonly)'},
    'kleidergren': {'label': 'Kleidergrößen:', 'type': 'Bool (Readonly)'},
    'krankenkasse': {'label': 'Krankenkasse', 'type': 'Text (Readonly)'},
    'krankentageJahr': {'label': 'KrankentageJahr', 'type': 'Ganzzahl (Readonly)'},
    'kreditinstitut': {'label': 'Kreditinstitut', 'type': 'Text'},
    'land': {'label': 'Land', 'type': 'Text'},
    'lastName': {'label': 'Nachname', 'type': 'Text (Readonly)'},
    'middleName': {'label': 'Zweiter Vorname', 'type': 'Text (Readonly)'},
    'modifiedAt': {'label': 'Geändert am', 'type': 'Datum-Uhrzeit (Readonly)'},
    'modifiedByName': {'label': 'Geändert von', 'type': 'Text (Readonly)'},
    'name': {'label': 'Name', 'type': 'Text (Readonly)'},
    'notfallTelefonnummer': {'label': 'Notfall Telefonnummer', 'type': 'Text'},
    'notfallnummerName': {'label': 'Notfallnummer Name', 'type': 'Text'},
    'ort': {'label': 'Ort', 'type': 'Text'},
    'personalausweisnummer': {'label': 'Personalausweisnummer', 'type': 'Text (Readonly)'},
    'personalnummer': {'label': 'Personalnummer', 'type': 'Text (Readonly)'},
    'phoneNumber': {'label': 'Telefon', 'type': 'Text'},
    'phoneNumberIsInvalid': {'label': 'Telefon ungültig', 'type': 'Bool (Readonly)'},
    'phoneNumberIsOptedOut': {'label': 'Telefon Opt-Out', 'type': 'Bool (Readonly)'},
    'pullovergre': {'label': 'Pullovergröße:', 'type': 'Text'},
    'qualifikation': {'label': 'Qualifikation', 'type': 'Liste (Readonly)'},
    'religionKonfession': {'label': 'Religion / Konfession', 'type': 'Text (Readonly)'},
    'rentenversicherungsnummer': {'label': 'Rentenversicherungsnummer', 'type': 'Text (Readonly)'},
    'salutationName': {'label': 'Anrede', 'type': 'Text (Readonly)'},
    'schuhgre': {'label': 'Schuhgröße:', 'type': 'Text'},
    'staatsname': {'label': 'Staatsangehörigkeit', 'type': 'Text (Readonly)'},
    'steuerklasse': {'label': 'Steuerklasse', 'type': 'Text (Readonly)'},
    'steuernummer': {'label': 'Steuernummer', 'type': 'Text (Readonly)'},
    'strasse': {'label': 'Strasse', 'type': 'Text'},
    'stundenlohnBrutto': {'label': 'Stundenlohn (brutto):', 'type': 'Text (Readonly)'},
    'tShirtGre': {'label': 'T-ShirtGröße:', 'type': 'Text'},
    'unterweisungen': {'label': 'Unterweisungen:', 'type': 'Bool (Readonly)'},
    'unterweisungen1': {'label': 'Unterweisungen', 'type': 'Liste (Readonly)'},
    'urlaubName': {'label': 'Urlaub', 'type': 'Text (Readonly)'},
    'userconnexName': {'label': 'Benutzerverbindung', 'type': 'Text (Readonly)'},
    'vertragsart': {'label': 'Vertragsart', 'type': 'Liste (Readonly)'},
    'westengre': {'label': 'Westengröße:', 'type': 'Text'},
    'zertifikat34a': {'label': 'Zertifikat 34a', 'type': 'Text (Readonly)'},
    'brandschutzZertifikat': {'label': 'Brandschutz Zertifikat', 'type': 'Text (Readonly)'},
  };
}
