# This file is generated by the Flutter engine and should not be edited.

def flutter_root
  # 1. Check if environment variable is set (typical for CI like Codemagic)
  return ENV['FLUTTER_ROOT'] if ENV['FLUTTER_ROOT'] && !ENV['FLUTTER_ROOT'].empty?

  # 2. Fallback: Parse Generated.xcconfig
  generated_xcconfig_file = File.expand_path(File.join('..', 'Generated.xcconfig'), __FILE__)
  if File.exist?(generated_xcconfig_file)
    File.foreach(generated_xcconfig_file) do |line|
      matches = line.match(/\s*FLUTTER_ROOT\s*=\s*(.*)/)
      return matches[1].strip if matches
    end
  end

  # 3. Final error
  raise "FLUTTER_ROOT not found. Ensure flutter pub get has run and FLUTTER_ROOT is set."
end

require File.expand_path(File.join('packages', 'flutter_tools', 'bin', 'podhelper'), flutter_root)
