# This file is generated by the Flutter engine and should not be edited.

def flutter_root
  generated_xcconfig_file = File.expand_path(File.join('..', 'Generated.xcconfig'), __FILE__)
  unless File.exist?(generated_xcconfig_file)
    raise "#{generated_xcconfig_file} must exist. If you're running pod install manually, make sure flutter pub get has been executed"
  end

  File.foreach(generated_xcconfig_file) do |line|
    matches = line.match(/\AFLUTTER_ROOT=(.*)\z/)
    return matches[1].strip if matches
  end
  raise "FLUTTER_ROOT not found in #{generated_xcconfig_file}. Try deleting Generated.xcconfig, then run flutter pub get"
end

require File.expand_path(File.join('packages', 'flutter_tools', 'bin', 'podhelper'), flutter_root)
